{"count":8,"days":[{"date":"2021-10-12T00:00:00.000Z","count":0,"incidents":[],"order":1},{"date":"2021-10-11T00:00:00.000Z","count":0,"incidents":[],"order":2},{"date":"2021-10-10T00:00:00.000Z","count":0,"incidents":[],"order":3},{"date":"2021-10-09T00:00:00.000Z","count":0,"incidents":[],"order":4},{"date":"2021-10-08T00:00:00.000Z","count":0,"incidents":[],"order":5},{"date":"2021-10-07T00:00:00.000Z","count":1,"incidents":[{"id":"77822711","title":"Rack Down","date":"2021-10-07T14:57:57.420Z","modified":"2021-10-12T14:04:42.275Z","scheduled":null,"severity":"major-outage","affectedsystems":["ion","director","mail","ras","cluster","storage","auth"],"resolved":false,"content":"<p>A UPS failure at approximately 9:26 this morning caused a server rack to shut down. Most servers have recovered, but some are still experiencing issues, including crucial portions of our infrastructure. We are working to resolve the issue.</p>\n<!--- language code: en -->\n"}],"order":6},{"date":"2021-10-06T00:00:00.000Z","count":0,"incidents":[],"order":7},{"date":"2021-10-05T00:00:00.000Z","count":0,"incidents":[],"order":8}],"daysSinceLatest":4}